### ISSUE TITLE
Cannot find the repository in README.md

### ISSUE THREAD

**Issue by purewater0901** [tud-amr/amr-lmpcc#1]
Hi!

I tried to build this package according to the description in README, however I cannot find the repositiory below.

```
git clone https://github.com/bbrito/amr-lmpcc.git
```

I think the repository might be private.

**Comment by bbrito** [comment]
I am sorry. The link you should clone is:
https://github.com/tud-amr/amr-lmpcc.gitThis link has not been clicked (https://github.com/tud-amr/amr-lmpcc.git)
I already updated the readme.
