### ISSUE TITLE
Compilation error with pedsim_ros

### ISSUE THREAD

**Issue by gaoyangu** [tud-amr/amr-lmpcc#3]
Greetings,
I tried to build this package according to the description in README, but I'm facing some issues.
When I catkin_make my workspace,  I get an error.

**/catkin_ws/src/pedsim_ros/pedsim_gazebo_plugin/src/actor_poses_plugin.cpp:8:46: fatal error: gazebo-9/gazebo/physics/physics.hh: No such file or directory
compilation terminated.**

I am using Ubuntu16.04 with ROS-Kinetic, and gazebo version 7.16.0.

Best,
gao

**Comment by ruficol** [comment]
你好，请问这个问题最后解决了吗。我也碰到一样的问题，physics.hh: 没有那个文件或目录。谢谢
