### ISSUE TITLE
Where can I find the original acado code used to generate C code

### ISSUE THREAD

**Issue by chentairan** [tud-amr/amr-lmpcc#7]
Hi @bbrito ,

I only found the acado generated C code in the directory `amr-lmpcc/lmpcc/src/generated_mpc`, I would like to read the acado ocp code (Code for generating C code), where is it please?

Thanks,
Chen Tairan

**Comment by bbrito** [comment]
You can find it here: [four_persons](https://github.com/bbrito/acado/tree/four_persons)

**Comment by chentairan** [comment]
Hi @bbrito ,

I find that the `bioreactor2.cpp` doesn't contain the free space and dynamic obstacles constraints. But in the [bioreactor.cpp](https://github.com/bbrito/acado/blob/four_persons/examples/ocp/bioreactor.cpp) has these. 

Could you please check which file is the right acado code?

Thanks,
Chen Tairan

**Comment by bbrito** [comment]
You are right. It is bioreactor.cpp.

I am sorry for this. I should have created a proper cpp for this and well documented but I did not have the time.

Best,
Bruno

**Comment by chentairan** [comment]
Fortunately I got the whole algorithm running.
I tried to generate C Code from bioreactor.cpp and found some subtle differences when comparing it with this project's ocp directory. But it doesn't affect me to read this code, thanks a lot.

I have another question, in mpc the reference path is read in through the [config file](https://github.com/tud-amr/amr-lmpcc/blob/master/lmpcc/config/lmpcc_config_parameter.yaml#L47), if I want to update the global path dynamically, do you have any suggestions to change it?

Best,
Chen Tairan

**Comment by bbrito** [comment]
Hi, you can use the global planner that comes with ros move_base. Then you can add a subscriber to that topic and update the path waypoints. I hope it helps!

**Comment by chentairan** [comment]
Thanks !
