### ISSUE TITLE
Robot doesn't avoid for moving person 

### ISSUE THREAD

**Issue by Geonhee-LEE** [tud-amr/amr-lmpcc#8]
Hi, @bbrito.
I tried to launch the `amr-lmpcc` according to your guide and built successfully. However, I found the robot didn't avoid the moving person. I just changed the source(`pedsim_ros/pedsim_visualizer/src/sim_visualizer.cpp`) since cakin_make fail. I watched `visualize_ellipses_array` topic didn't visualize on RViz. Is it related to this situation?

https://user-images.githubusercontent.com/12562147/159816238-2de24197-c901-4084-9d6f-5a958de34f90.mp4

**Comment by Geonhee-LEE** [comment]
![image](https://user-images.githubusercontent.com/12562147/159817316-f64a9992-0a7c-4d0c-97f0-5e8dcb275cb4.png)

**Comment by Geonhee-LEE** [comment]
some error:

- `roslaunch pedsim_simulator corridor.launch` :
    ![image](https://user-images.githubusercontent.com/12562147/159817384-c34960a0-5cd6-41e7-a3ca-85616dc47042.png)

- `roslaunch lmpcc_obstacle_feed lmpcc_obstacle_feed.launch`:    
    ![image](https://user-images.githubusercontent.com/12562147/159817521-d757a3e3-f645-4785-b0dc-421605c1a310.png)

**Comment by bbrito** [comment]
I think you have a conflict with msg type as TrackedPersons msg appears in two different packages: pedsim_msgs and spencer_tracking_msgs. The format is the same for both msgs. My suggestion is for you to upadte lmpcc_obstacle feed to use the right type. You only need to change the header files, the function headers and cmake. Otherwise you should make sure that the simulator of pedestrian publishes the right type. I guess you have the wrong simulator branch. Hope it helps!

**Comment by Geonhee-LEE** [comment]
@bbrito Thanks for rely!
I have tried to solve it for now and finally found the difference between `spencer_tracking_msgs::TrackedPerson` and `pedsim_msgs::TrackedPerson`. But, your bbrito/pedsim_ros/four_persons branch is recommended.
I changed branch from `four_persons` to `master`. I wonder what is the role about
 [geometry_msgs/Pose goal](https://github.com/bbritopedsim_rospedsim_ros/blob/four_persons/pedsim_msgs/msg/TrackedPerson.msg) which is included in `four_persons`.

The result was something strange. Robot doesn't move never. 

https://user-images.githubusercontent.com/12562147/159843658-d6c2386f-8da1-457e-9b7c-e2c8de5fef20.mp4

**Comment by bbrito** [comment]
Please keep using the four_persons branch. You just need to fix the msg interface in one side. You can do it on lmpcc side.

**Comment by Geonhee-LEE** [comment]
> Please keep using the four_persons branch. You just need to fix the msg interface in one side. You can do it on lmpcc side.

@bbrito Thanks for reply.
The error occur on `pedsim_ros/pedsim_visualizer/src/sim_visualizer.cpp`. How to fix the build error if will change nterface on lmpcc side?
Otherwise, did I misunderstand about your advice?

![image](https://user-images.githubusercontent.com/12562147/160307427-8157df44-430e-4b4f-87e3-f9e3517df8a5.png)

**Comment by bbrito** [comment]
You can comment out those two lines. It will fix the issue.

**Comment by ruficol** [comment]
> I think you have a conflict with msg type as TrackedPersons msg appears in two different packages: pedsim_msgs and spencer_tracking_msgs. The format is the same for both msgs. My suggestion is for you to upadte lmpcc_obstacle feed to use the right type. You only need to change the header files, the function headers and cmake. Otherwise you should make sure that the simulator of pedestrian publishes the right type. I guess you have the wrong simulator branch. Hope it helps!

![2023-03-29 00-20-19屏幕截图](https://user-images.githubusercontent.com/92928798/228305186-876bb8ee-6bcd-4b19-8b7b-1cdf52c4d2c3.png)
![2023-03-29 00-25-23屏幕截图](https://user-images.githubusercontent.com/92928798/228306113-265f22ba-2f18-4738-82aa-b33f4ebb826d.png)

Hi, I have encountered the same error. And the robot doesn't move.
But I don't know how to update lmpcc_obstacle feed to use the right type, can you tell me how to update the msg type, thank you.

**Comment by bbrito** [comment]
exactly that should fix it. please make a PR with the fix if you do it.
