### ISSUE TITLE
objective function source

### ISSUE THREAD

**Issue by Geonhee-LEE** [tud-amr/amr-lmpcc#9]
Hi, @bbrito. Thanks for your contribution!
I am keeping to trying to review your source to find `objective function` parts. But, I didn't find that parts although spend a lot of times. After that, I recently wonder that `generated_mpc` and `ocp` folders exist as libraries without C++ sources which were already compiled. 
If not, would you let me know where it exists?

Regards,

**Comment by truncs** [comment]
Wondering the same.

**Comment by bbrito** [comment]
Hi! You can find the solver code [here](https://github.com/bbrito/acado). 

branch: four_persons
[file](https://github.com/bbrito/acado/blob/four_persons/examples/ocp/bioreactor.cpp):

This is not ideal but that is what i can provide. I'll update the readme. sorry for the trouble.
